require('dotenv').config({ path: require('path').join(__dirname, '../.env') })
const mongoose = require('mongoose')
const Product = require('../models/product')

const products = [
  {
    name: 'Samsung Galaxy S24 Ultra (512GB)',
    price: 1199.99,
    originalPrice: 1399.99,
    category: 'Smartphones',
    model: 'Galaxy S24 Ultra AI',
    sku: 'SM-S24U-512',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    description: 'Flagship Galaxy smartphone featuring Galaxy AI, titanium frame, 200MP camera, and built-in S Pen with Snapdragon 8 Gen 3.',
    stock: 25,
    inStock: true,
    featured: true,
    rating: 4.9,
    reviewCount: 418,
    colors: ['#333333', '#e5e7eb', '#d4af37'],
    highlights: ['200MP Quad Telephoto Camera', 'Snapdragon 8 Gen 3 for Galaxy', 'Built-in S-Pen & Titanium Frame', '7 Years OS Updates'],
    seoTitle: 'Samsung Galaxy S24 Ultra Titanium - Official Tech Innovation Store',
  },
  {
    name: 'Apple iPhone 15 Pro Max (256GB)',
    price: 1099.99,
    originalPrice: 1199.99,
    category: 'Smartphones',
    model: 'iPhone 15 Pro Max',
    sku: 'APL-IP15PM-256',
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    description: 'Aerospace-grade titanium design with A17 Pro chip, customizable Action button, 48MP main camera with 5x telephoto optical zoom.',
    stock: 30,
    inStock: true,
    featured: true,
    rating: 4.9,
    reviewCount: 520,
    colors: ['#4b5563', '#1e293b', '#e2e8f0'],
    highlights: ['A17 Pro chip with 6-core GPU', 'Action button & Super Retina XDR', 'USB-C with USB 3 speeds', '5x Optical Zoom'],
    seoTitle: 'Apple iPhone 15 Pro Max Natural Titanium - Official Tech Store',
  },
  {
    name: 'Google Pixel 8 Pro (128GB)',
    price: 899.99,
    originalPrice: 999.99,
    category: 'Smartphones',
    model: 'Pixel 8 Pro AI',
    sku: 'GOOG-P8P-128',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&q=80',
    description: 'Google Tensor G3 powered flagship phone with advanced Google AI photography, Super Actua display, and all-day battery.',
    stock: 20,
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 290,
    colors: ['#0f172a', '#38bdf8', '#f1f5f9'],
    highlights: ['Google Tensor G3 & AI Magic Editor', '6.7-inch Super Actua 120Hz display', 'Temperature sensor', 'All-day battery & Fast Charging'],
    seoTitle: 'Google Pixel 8 Pro 128GB - Tech Innovation.pk',
  },
  {
    name: 'Wireless Headphones',
    price: 129.99,
    originalPrice: 179.99,
    category: 'Audio',
    model: 'NoiseMax H1',
    sku: 'WH-001',
    image: '/images/wireless_headphones.webp',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life.',
    stock: 45,
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 312,
    colors: ['#0b0f1a', '#1f3b73', '#e5e7eb'],
    highlights: ['Active noise canceling', '30-hour battery', 'Low-latency mode'],
  },
  {
    name: 'Portable Speaker',
    price: 79.99,
    originalPrice: 119.99,
    category: 'Audio',
    model: 'Boom360 X',
    sku: 'PS-360',
    image: '/images/speaker.webp',
    description: 'Waterproof Bluetooth speaker with 360-degree sound and deep bass.',
    stock: 28,
    inStock: true,
    featured: true,
    rating: 4.7,
    reviewCount: 187,
    colors: ['#0f172a', '#7c3aed', '#e2e8f0'],
    highlights: ['IPX7 waterproof', '360-degree audio', '18-hour playtime'],
  },
  {
    name: 'Smart Watch',
    price: 299.99,
    originalPrice: 349.99,
    category: 'Wearables',
    model: 'PulseTrack S9',
    sku: 'SW-009',
    image: '/images/smart_watches.webp',
    description: 'Advanced smartwatch with fitness tracking, heart rate monitoring, and GPS.',
    stock: 32,
    inStock: true,
    featured: true,
    rating: 4.6,
    reviewCount: 205,
    colors: ['#111827', '#2563eb', '#f8fafc'],
    highlights: ['Always-on display', 'Water resistant', '7-day battery'],
  },
  {
    name: 'Wrist Watch',
    price: 89.99,
    originalPrice: 139.99,
    category: 'Wearables',
    model: 'Chrono Steel A1',
    sku: 'WW-180',
    image: '/images/wristwatch.jpg',
    description: 'Elegant stainless steel analog wristwatch with a refined finish.',
    stock: 52,
    inStock: true,
    featured: false,
    rating: 4.6,
    reviewCount: 102,
    colors: ['#0f172a', '#d4af37', '#e5e7eb'],
    highlights: ['Sapphire glass', 'Stainless steel', 'Water resistant'],
  },
  {
    name: '4K Webcam',
    price: 159.99,
    originalPrice: 219.99,
    category: 'Electronics',
    model: 'StreamCam 4K Pro',
    sku: 'WC-4K1',
    image: '/images/webcam.jpg',
    description: 'Ultra HD 4K webcam for streaming and video calls with sharp autofocus.',
    stock: 18,
    inStock: true,
    featured: true,
    rating: 4.5,
    reviewCount: 76,
    colors: ['#111827', '#1d4ed8', '#e5e7eb'],
    highlights: ['4K resolution', 'Auto focus', 'Wide-angle lens'],
  },
  {
    name: 'USB-C Cable',
    price: 12.99,
    originalPrice: 19.99,
    category: 'Accessories',
    model: 'ChargeFlex 6FT',
    sku: 'UCC-001',
    image: '/images/usb.png',
    description: 'Fast charging USB-C cable, 6ft length, braided for durability.',
    stock: 150,
    inStock: true,
    featured: false,
    rating: 4.4,
    reviewCount: 98,
    colors: ['#111827', '#4b5563', '#f3f4f6'],
    highlights: ['Fast charging', '6ft length', 'Braided nylon'],
  },
  {
    name: 'Leather Wallet',
    price: 49.99,
    originalPrice: 69.99,
    category: 'Accessories',
    model: 'RFID Bifold Slim',
    sku: 'LW-110',
    image: '/images/wallet.jpg',
    description: 'Genuine leather bifold wallet with RFID protection and clean stitching.',
    stock: 72,
    inStock: true,
    featured: false,
    rating: 4.5,
    reviewCount: 88,
    colors: ['#111827', '#92400e', '#e5e7eb'],
    highlights: ['RFID protection', 'Full-grain leather', 'Slim profile'],
  },
  {
    name: 'Sunglasses',
    price: 79.99,
    originalPrice: 109.99,
    category: 'Accessories',
    model: 'UV400 Polar',
    sku: 'SG-220',
    image: '/images/sunglasses.webp',
    description: 'UV protection polarized sunglasses with lightweight frames.',
    stock: 48,
    inStock: true,
    featured: false,
    rating: 4.4,
    reviewCount: 67,
    colors: ['#111827', '#0ea5e9', '#f8fafc'],
    highlights: ['Polarized lenses', 'UV400 protection', 'Featherweight frame'],
  },
  {
    name: 'Baseball Cap',
    price: 19.99,
    originalPrice: 29.99,
    category: 'Accessories',
    model: 'Classic Fit Cap',
    sku: 'BC-140',
    image: '/images/cap.jpg',
    description: 'Classic baseball cap in various colors with a structured crown.',
    stock: 94,
    inStock: true,
    featured: false,
    rating: 4.3,
    reviewCount: 54,
    colors: ['#111827', '#2563eb', '#ef4444', '#f8fafc'],
    highlights: ['Adjustable strap', 'Structured fit', 'Breathable panels'],
  },
  {
    name: 'Backpack',
    price: 64.99,
    originalPrice: 99.99,
    category: 'Accessories',
    model: 'TravelPack 30L',
    sku: 'BP-300',
    image: '/images/bagpack.jpg',
    description: 'Durable 30L laptop backpack with USB port and organized compartments.',
    stock: 38,
    inStock: true,
    featured: false,
    rating: 4.7,
    reviewCount: 133,
    colors: ['#0f172a', '#1d4ed8', '#e5e7eb'],
    highlights: ['30L capacity', 'Laptop sleeve', 'USB charging port'],
  },
  {
    name: 'Cotton T-Shirt',
    price: 24.99,
    originalPrice: 34.99,
    category: 'Clothing',
    model: 'Classic Cotton Tee',
    sku: 'CT-100',
    image: '/images/cotton_tshirt.jpg',
    description: '100% premium cotton t-shirt, breathable and soft for daily wear.',
    stock: 85,
    inStock: true,
    featured: false,
    rating: 4.6,
    reviewCount: 143,
    colors: ['#111827', '#ef4444', '#f8fafc', '#10b981'],
    highlights: ['Soft cotton', 'Pre-shrunk fit', 'Easy care'],
  },
  {
    name: 'Denim Jeans',
    price: 59.99,
    originalPrice: 89.99,
    category: 'Clothing',
    model: 'Slim Fit Denim',
    sku: 'DJ-200',
    image: '/images/jeans.webp',
    description: 'Classic slim-fit denim jeans with comfortable stretch fabric.',
    stock: 60,
    inStock: true,
    featured: false,
    rating: 4.5,
    reviewCount: 119,
    colors: ['#1e3a8a', '#111827', '#64748b'],
    highlights: ['Stretch denim', 'Slim fit', 'Reinforced seams'],
  },
  {
    name: 'Casual Hoodie',
    price: 49.99,
    originalPrice: 74.99,
    category: 'Clothing',
    model: 'Cozy Fleece Pullover',
    sku: 'HD-300',
    image: '/images/hoodie.jpg',
    description: 'Warm and comfortable fleece hoodie with front pocket and drawstring hood.',
    stock: 40,
    inStock: true,
    featured: false,
    rating: 4.7,
    reviewCount: 162,
    colors: ['#111827', '#6b7280', '#0284c7'],
    highlights: ['Fleece interior', 'Front kangaroo pocket', 'Durable drawstrings'],
  },
  {
    name: 'Winter Jacket',
    price: 119.99,
    originalPrice: 159.99,
    category: 'Clothing',
    model: 'Thermal Puffer Pro',
    sku: 'WJ-400',
    image: '/images/jacket.jpg',
    description: 'Insulated water-resistant winter jacket for maximum warmth and style.',
    stock: 22,
    inStock: true,
    featured: false,
    rating: 4.8,
    reviewCount: 95,
    colors: ['#0f172a', '#047857', '#b91c1c'],
    highlights: ['Water-resistant shell', 'Thermal down insulation', 'Zippered pockets'],
  },
  {
    name: 'Running Shoes',
    price: 89.99,
    originalPrice: 129.99,
    category: 'Shoes',
    model: 'AeroStep Pro',
    sku: 'SH-500',
    image: '/images/shoes.jpg',
    description: 'Lightweight cushioned running shoes with breathable mesh and responsive grip.',
    stock: 50,
    inStock: true,
    featured: false,
    rating: 4.7,
    reviewCount: 210,
    colors: ['#0f172a', '#2563eb', '#ef4444'],
    highlights: ['Responsive foam cushion', 'Breathable mesh', 'Anti-slip rubber sole'],
  },
]

async function seedDatabase() {
  try {
    const uri = process.env.MONGO_URI || process.env.MONGODB_URI || 'mongodb://localhost:27017/ecommerce'
    await mongoose.connect(uri)
    console.log('MongoDB connected for seeding')

    await Product.deleteMany({})
    console.log('Previous products cleared')

    await Product.insertMany(products)
    console.log(`${products.length} products seeded successfully`)

    await mongoose.connection.close()
  } catch (err) {
    console.error('Seeding error:', err.message)
    process.exit(1)
  }
}

if (require.main === module) {
  seedDatabase()
}

module.exports = { products, seedDatabase }
