require('dotenv').config({ path: require('path').join(__dirname, '../.env') })
const mongoose = require('mongoose')
const Product = require('../models/product')

const products = [
  {
    name: 'Wireless Headphones',
    price: 129.99,
    originalPrice: 179.99,
    category: 'Electronics',
    image: '/images/wireless_headphones.webp',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life.',
    stock: 45,
    inStock: true,
    rating: 4.8,
    reviewCount: 312,
    colors: ['#0b0f1a', '#1f3b73', '#e5e7eb'],
    highlights: ['Active noise canceling', '30-hour battery', 'Low-latency mode'],
  },
  {
    name: 'Smart Watch',
    price: 299.99,
    originalPrice: 349.99,
    category: 'Electronics',
    image: '/images/smart_watches.webp',
    description: 'Advanced smartwatch with fitness tracking, heart rate monitoring, and GPS.',
    stock: 32,
    inStock: true,
    rating: 4.6,
    reviewCount: 205,
    colors: ['#111827', '#2563eb', '#f8fafc'],
    highlights: ['Always-on display', 'Water resistant', '7-day battery'],
  },
  {
    name: 'USB-C Cable',
    price: 12.99,
    originalPrice: 19.99,
    category: 'Electronics',
    image: '/images/usb.png',
    description: 'Fast charging USB-C cable, 6ft length, braided for durability.',
    stock: 150,
    inStock: true,
    rating: 4.4,
    reviewCount: 98,
    colors: ['#111827', '#4b5563', '#f3f4f6'],
    highlights: ['Fast charging', '6ft length', 'Braided nylon'],
  },
  {
    name: 'Portable Speaker',
    price: 79.99,
    originalPrice: 119.99,
    category: 'Electronics',
    image: '/images/speaker.webp',
    description: 'Waterproof Bluetooth speaker with 360-degree sound and deep bass.',
    stock: 28,
    inStock: true,
    rating: 4.7,
    reviewCount: 187,
    colors: ['#0f172a', '#7c3aed', '#e2e8f0'],
    highlights: ['IPX7 waterproof', '360-degree audio', '18-hour playtime'],
  },
  {
    name: '4K Webcam',
    price: 159.99,
    originalPrice: 219.99,
    category: 'Electronics',
    image: '/images/webcam.jpg',
    description: 'Ultra HD 4K webcam for streaming and video calls with sharp autofocus.',
    stock: 18,
    inStock: true,
    rating: 4.5,
    reviewCount: 76,
    colors: ['#111827', '#1d4ed8', '#e5e7eb'],
    highlights: ['4K resolution', 'Auto focus', 'Wide-angle lens'],
  },
  {
    name: 'Cotton T-Shirt',
    price: 24.99,
    originalPrice: 34.99,
    category: 'Clothing',
    image: '/images/cotton_tshirt.jpg',
    description: '100% premium cotton t-shirt, breathable and soft for daily wear.',
    stock: 85,
    inStock: true,
    rating: 4.6,
    reviewCount: 143,
    colors: ['#111827', '#ef4444', '#f8fafc', '#10b981'],
    highlights: ['Soft cotton', 'Pre-shrunk fit', 'Easy care'],
  },
  {
    name: 'Denim Jeans',
    price: 59.99,
    originalPrice: 89.99,
    category: 'Clothing',
    image: '/images/jeans.webp',
    description: 'Classic blue denim jeans with a comfortable modern fit.',
    stock: 62,
    inStock: true,
    rating: 4.5,
    reviewCount: 121,
    colors: ['#1e3a8a', '#0f172a', '#9ca3af'],
    highlights: ['Stretch denim', 'Reinforced seams', 'Modern taper'],
  },
  {
    name: 'Casual Hoodie',
    price: 49.99,
    originalPrice: 74.99,
    category: 'Clothing',
    image: '/images/hoodie.jpg',
    description: 'Soft fleece hoodie perfect for any season, with a structured silhouette.',
    stock: 44,
    inStock: true,
    rating: 4.7,
    reviewCount: 164,
    colors: ['#111827', '#6d28d9', '#e5e7eb'],
    highlights: ['Heavyweight fleece', 'Double-lined hood', 'Kangaroo pocket'],
  },
  {
    name: 'Running Shoes',
    price: 89.99,
    originalPrice: 129.99,
    category: 'Shoes',
    image: '/images/shoes.jpg',
    description: 'Professional running shoes with cushioned sole and breathable mesh.',
    stock: 56,
    inStock: true,
    rating: 4.6,
    reviewCount: 210,
    colors: ['#0f172a', '#2563eb', '#f97316'],
    highlights: ['Responsive cushioning', 'Breathable mesh', 'Grip outsole'],
  },
  {
    name: 'Winter Jacket',
    price: 129.99,
    originalPrice: 189.99,
    category: 'Clothing',
    image: '/images/jacket.jpg',
    description: 'Warm waterproof winter jacket with insulated lining and storm guards.',
    stock: 35,
    inStock: true,
    rating: 4.8,
    reviewCount: 97,
    colors: ['#0f172a', '#0ea5e9', '#f8fafc'],
    highlights: ['Waterproof shell', 'Thermal insulation', 'Windproof cuffs'],
  },
  {
    name: 'Leather Wallet',
    price: 34.99,
    originalPrice: 49.99,
    category: 'Accessories',
    image: '/images/wallet.jpg',
    description: 'Genuine leather bifold wallet with RFID protection and clean stitching.',
    stock: 72,
    inStock: true,
    rating: 4.5,
    reviewCount: 88,
    colors: ['#111827', '#92400e', '#e5e7eb'],
    highlights: ['RFID protection', 'Full-grain leather', 'Slim profile'],
  },
  {
    name: 'Sunglasses',
    price: 79.99,
    originalPrice: 109.99,
    category: 'Accessories',
    image: '/images/sunglasses.webp',
    description: 'UV protection polarized sunglasses with lightweight frames.',
    stock: 48,
    inStock: true,
    rating: 4.4,
    reviewCount: 67,
    colors: ['#111827', '#0ea5e9', '#f8fafc'],
    highlights: ['Polarized lenses', 'UV400 protection', 'Featherweight frame'],
  },
  {
    name: 'Baseball Cap',
    price: 19.99,
    originalPrice: 29.99,
    category: 'Accessories',
    image: '/images/cap.jpg',
    description: 'Classic baseball cap in various colors with a structured crown.',
    stock: 94,
    inStock: true,
    rating: 4.3,
    reviewCount: 54,
    colors: ['#111827', '#2563eb', '#ef4444', '#f8fafc'],
    highlights: ['Adjustable strap', 'Structured fit', 'Breathable panels'],
  },
  {
    name: 'Backpack',
    price: 64.99,
    originalPrice: 99.99,
    category: 'Accessories',
    image: '/images/bagpack.jpg',
    description: 'Durable 30L laptop backpack with USB port and organized compartments.',
    stock: 38,
    inStock: true,
    rating: 4.7,
    reviewCount: 133,
    colors: ['#0f172a', '#1d4ed8', '#e5e7eb'],
    highlights: ['30L capacity', 'Laptop sleeve', 'USB charging port'],
  },
  {
    name: 'Wrist Watch',
    price: 89.99,
    originalPrice: 139.99,
    category: 'Accessories',
    image: '/images/wristwatch.jpg',
    description: 'Elegant stainless steel analog wristwatch with a refined finish.',
    stock: 52,
    inStock: true,
    rating: 4.6,
    reviewCount: 102,
    colors: ['#0f172a', '#d4af37', '#e5e7eb'],
    highlights: ['Sapphire glass', 'Stainless steel', 'Water resistant'],
  },
]

async function seedDatabase() {
  try {
    await mongoose.connect(
      process.env.MONGODB_URI || 'mongodb://localhost:27017/ecommerce',
    )
    console.log('MongoDB connected')

    await Product.deleteMany({})
    console.log('Previous products cleared')

    await Product.insertMany(products)
    console.log(`${products.length} products seeded successfully`)

    await mongoose.connection.close()
  } catch (err) {
    console.error('Seeding error:', err.message)
    process.exit(1)
  }
}

seedDatabase()
